
services:
  databases:
    image: postgres:16-bullseye
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - progressDB:/var/lib/postgresql/data
      - /var/run:/var/run
    env_file: development.env
    restart: always

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    depends_on:
      - databases
    volumes:
      - pgAdminData:/var/lib/pgadmin
    env_file: development.pgadmin.env
    ports:
      - "5050:5050"


#  frontend:
#    container_name: rustify_frontend
#    image: node:20-alpine
#    volumes:
#      - ./wg_frontend:/wg_frontend
#    environment:
#      - PORT=4200
#    command: ["node","/wg_frontend/server/server.mjs"]
#    networks:
#      - traefik-public
#
#    labels:
#      - traefik.enable=true
#      - traefik.docker.network=traefik-public
#      - traefik.constraint-label=traefik-public
#      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.rule=PathPrefix(`/`)
#      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.entrypoints=http
#      - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=4200



networks:
  traefik-public:
    external: true
  private:
    internal: true
    external: false

volumes:
  progressDB:
  pgAdminData:
#secrets:
