### GET request to example server
POST http://localhost:3000/api/v1/auth/login/access-token
Content-Type: application/x-www-form-urlencoded

username = defalt4 &
password = 6367411

### Register user
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "username": "defaslts4",
  "password": "6367411"
}

###  peers rxtx
GET http://localhost:3000/api/v1/peers/rxtx
Cookie: jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTgzNjM0MjQsImlhdCI6MTcxODM2MzI0NCwiYXV0aCI6ImRlZmFsdDQifQ.yjJNFYUqKqfm-QC1RkCFdOtFBtbiNzRF5GZo98Q2DCs


### create peer
POST http://localhost:3000/api/v1/peer
Content-Type: application/json
Cookie: jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTgzNTg4NDYsImlhdCI6MTcxODM1ODY2NiwiYXV0aCI6ImRlZmFsdCJ9.riaeLpWtcg7pQ3xF1IfT4uAse_sHaOpKI528EzXrAXY

{
  "name": "test peer2",
  "enabled": "false"
}

### list peer
GET http://localhost:3000/api/v1/peer?enabled=true&name_contains=
Content-Type: application/json
Cookie: jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTgzNTg4NDYsImlhdCI6MTcxODM1ODY2NiwiYXV0aCI6ImRlZmFsdCJ9.riaeLpWtcg7pQ3xF1IfT4uAse_sHaOpKI528EzXrAXY


### update peer
PATCH http://localhost:3000/api/v1/peer/30ed0ced-d68e-42b0-8b15-5c9d6626d3d8
Content-Type: application/json
Cookie: jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTgzNTg4NDYsImlhdCI6MTcxODM1ODY2NiwiYXV0aCI6ImRlZmFsdCJ9.riaeLpWtcg7pQ3xF1IfT4uAse_sHaOpKI528EzXrAXY

{
  "name": "updated name1"
}